# Generated by Django 4.2.3 on 2023-07-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('archivo_imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
