# Generated by Django 4.2.3 on 2023-07-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicboxApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_Reciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenido', models.IntegerField()),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('hora_fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp.usuario')),
            ],
        ),
    ]
