# Generated by Django 4.2.3 on 2023-07-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicboxApp', '0002_actividad_reciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_interaccion', to='musicboxApp.usuario')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido_interaccion', to='musicboxApp.usuario')),
            ],
        ),
    ]
