# Generated by Django 4.2.3 on 2023-07-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link_referencia', models.CharField(max_length=100)),
                ('archivo_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link_referencia', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=10000)),
                ('archivo_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('archivo_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10000)),
                ('puntaje', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.album')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=10000)),
                ('archivo_imagen', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_interaccion', to='musicboxApp2.usuario')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido_interaccion', to='musicboxApp2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.album')),
            ],
        ),
        migrations.CreateModel(
            name='Artistas_Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.artista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Albums_x_Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.album')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.lista')),
            ],
        ),
        migrations.CreateModel(
            name='Albums_Favorits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.album')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.artista'),
        ),
        migrations.CreateModel(
            name='Actividad_Reciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenido', models.IntegerField()),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('hora_fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxApp2.usuario')),
            ],
        ),
    ]
